version: '2'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: _055_OMS
  
  teamcity:
    image: jetbrains/teamcity-server
    hostname: teamcity
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/data/log:/opt/teamcity/logs
  
  jboss:
    image: jboss7:java6
    hostname: jboss
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./deploy:/opt/jboss/standalone/deployments