version: '2'

services:
  mysql:
    image: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: _055_OMS

  teamcity:
    image: jetbrains/teamcity-server
    hostname: teamcity
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/data/log:/opt/teamcity/logs
