---
# docker yml file
- name: Update sourse list
  apt: update_cache=yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list and update
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes

- name: Install DockerCE
  apt: name={{ item }}
  with_items:
    - docker-ce
    - mysql-client

- name: Install docker-compose   
  copy:
    src: docker-compose
    dest: /usr/local/bin
    mode: "u=rx,g=rx,o=x"
    force: yes


- name: Start docker-compose file
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /oms/